In [36]:
import math
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib import style
style.use('ggplot')

In [57]:
horas = ['9-10', '10-11', '11-12', '12-13', '13-14', '14-15', '15-16', '16-17', '17-18', '18-19']
lambdas = [50, 60, 58, 43, 35, 31, 44, 59, 65, 23]
h_h = [13.64, 13.64,13.64,13.64,13.64,13.64,13.64,13.64,13.64,13.64]
c_e = [27.29,27.29,27.29,27.29,27.29,27.29,27.29,27.29,27.29,27.29,27.29,27.29, ]

df = pd.DataFrame({
    'hora':horas,
    'lambda':lambdas,
    'h_h':h_h
})
df

    hora  lambda    h_h
0   9-10      50  13.64
1  10-11      60  13.64
2  11-12      58  13.64
3  12-13      43  13.64
4  13-14      35  13.64
5  14-15      31  13.64
6  15-16      44  13.64
7  16-17      59  13.64
8  17-18      65  13.64
9  18-19      23  13.64

In [38]:
# Mezcla de operaciones
# probs = [0.33, 0.28, 0.25, 0.07, 0.03]
# tiempos = [4, 2, 2, 4, 8]

In [39]:
def calcular_mu(probs, tiempos):
    """
    Calcula la tasa de servicio μ (clientes por hora)
    a partir de probabilidades y tiempos promedio (en minutos).
    """
    
    # Probabilidad conocida
    p_conocida = sum(probs)
    
    # Tiempo promedio ponderado conocido
    t_prom_conocido = sum(p * t for p, t in zip(probs, tiempos))
    
    # Probabilidad restante
    p_rest = 1 - p_conocida
    
    # Tiempo promedio del resto (ajuste proporcional)
    t_resto = t_prom_conocido / p_conocida
    
    # Tiempo promedio total
    t_prom_min = t_prom_conocido + p_rest * t_resto
    
    # Convertimos a clientes por hora
    mu = 60 / t_prom_min
    
    return mu

In [40]:

def metricas_mmc(lam, mu, c):

    r = lam / mu
    rho = lam / (c * mu)

    if rho >= 1:
        return None, None, None, None, None, None, None, None

    suma = sum((r**k)/math.factorial(k) for k in range(c))
    termino_final = (r**c)/(math.factorial(c)*(1-rho))
    P0 = 1/(suma + termino_final)

    Lq = (P0 * (r**c) * rho) / (math.factorial(c) * (1-rho)**2)

    
    Wq_h = Lq / lam
    Ws_h = Wq_h + (1/mu)
    Ls = lam * Ws_h
    Wq_m = Wq_h * 60
    Ws_m = Ws_h * 60

    return rho, P0, Lq, Wq_h, Ws_h, Ls, Wq_m, Ws_m

In [41]:
# frecuencia de operaciones 9-10
probs09_10 = [0.36, 0.18, 0.23, 0.09, 0.02, 0.04]
tiempos09_10 = [4, 2, 2, 4, 8]

# frecuencia de operaciones 10-11
probs10_11 = [0.36, 0.16, 0.21, 0.1, 0.04, 0.04]
tiempos10_11 = [4, 2, 2, 4, 8]

# frecuencia de operaciones 11-12
probs11_12 = [0.36, 0.17, 0.20, 0.10, 0.04, 0.04]
tiempos11_12 = [4, 2, 2, 4, 8]

# frecuencia de operaciones 12-13
probs12_13 = [0.36, 0.17, 0.20, 0.10, 0.05, 0.05]
tiempos12_13 = [4, 2, 2, 4, 8]

# frecuencia de operaciones 13-14
probs13_14 = [0.35, 0.19, 0.27, 0.10, 0.04, 0.05]
tiempos13_14 = [4, 2, 2, 4, 8]

# frecuencia de operaciones 14-15
probs14_15 = [0.37, 0.21, 0.22, 0.10, 0.04, 0.05]
tiempos14_15 = [4, 2, 2, 4, 8]

# frecuencia de operaciones 15-16
probs15_16 = [0.39, 0.19, 0.19, 0.10, 0.03, 0.05]
tiempos15_16 = [4, 2, 2, 4, 8]

# frecuencia de operaciones 16-17
probs16_17 = [0.36, 0.19, 0.17, 0.10, 0.04, 0.04]
tiempos16_17 = [4, 2, 2, 4, 8]

# frecuencia de operaciones 17-18
probs17_18 = [0.30, 0.19, 0.16, 0.13, 0.06, 0.03]
tiempos17_18 = [4, 2, 2, 4, 8]

probs18_17 = [0.30, 0.19, 0.16, 0.13, 0.06, 0.03]
tiempos17_18 = [4, 2, 2, 4, 8]

tipos = ["DEPOSITO", "COBRANZAS LOCALES OTRAS AGENCIAS", "RETIRO", "COBRANZAS", "DESEMBOLSOS", "APERTURA"]

df_operaciones = pd.DataFrame({
    "Operacion": tipos,
    "Tiempo_min": [2.5, 2.5, 2.5, 4.8, 20, 2.2],
    "9-10": probs09_10,
    "10-11": probs10_11,
    "11-12": probs11_12,
    "12-13": probs12_13,
    "13-14": probs13_14,
    "14-15": probs14_15,
    "15-16": probs15_16,
    "16-17": probs16_17,
    "17-18": probs17_18,
    "18-19":probs18_17
})

df_operaciones

,Operacion,Tiempo_min,9-10,10-11,11-12,12-13,13-14,14-15,15-16,16-17,17-18,18-19
0,DEPOSITO,2.5,0.36,0.36,0.36,0.36,0.35,0.37,0.39,0.36,0.30,0.30
1,COBRANZAS LOCALES OTRAS AGENCIAS,2.5,0.18,0.16,0.17,0.17,0.19,0.21,0.19,0.19,0.19,0.19
2,RETIRO,2.5,0.23,0.21,0.20,0.20,0.27,0.22,0.19,0.17,0.16,0.16
3,COBRANZAS,4.8,0.09,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.13,0.13
4,DESEMBOLSOS,20.0,0.02,0.04,0.04,0.05,0.04,0.04,0.03,0.04,0.06,0.06
5,APERTURA,2.2,0.04,0.04,0.04,0.05,0.05,0.05,0.05,0.04,0.03,0.03

In [46]:
# df["mu"] = df.apply(lambda row: calcular_mu(probs, tiempos), axis=1)
mu_por_hora = {}

tiempos = df_operaciones["Tiempo_min"].values

for hora in df_operaciones.columns[2:]:  # saltamos Operacion y Tiempo_min
    probs = df_operaciones[hora]
    mu_por_hora[hora] = calcular_mu(probs, tiempos)



df["mu"] = df["hora"].map(mu_por_hora)

df["s"] = 5


df[["rho","P0","Lq","Wq_h","Ws_h","Ls", "Wq_m", "Ws_m"]] = df.apply(
    lambda row: metricas_mmc(row["lambda"], row["mu"], row["s"]),
    axis=1,
    result_type="expand"
)

df

,hora,lambda,mu,s,rho,P0,Lq,Wq_h,Ws_h,Ls,...,Ws_m,s_o,rho_o,P0_o,Lq_o,Wq_h_o,Ws_h_o,Ls_o,Wq_m_o,Ws_m_o
0,9-10,50,19.402460,5,0.515399,0.073847,0.153493,0.003070,0.054610,2.730486,...,3.276583,4.0,0.644248,0.067047,0.627159,0.012543,0.064083,3.204152,0.752591,3.844982
1,10-11,60,17.099906,5,0.701758,0.025614,0.895652,0.014928,0.073407,4.404443,...,4.404443,5.0,0.701758,0.025614,0.895652,0.014928,0.073407,4.404443,0.895652,4.404443
2,11-12,58,17.099906,5,0.678366,0.029591,0.725931,0.012516,0.070996,4.117762,...,4.259754,4.0,0.847958,0.018897,3.822626,0.065907,0.124387,7.214457,3.954441,7.463232
3,12-13,43,16.339678,5,0.526326,0.069682,0.171933,0.003998,0.065199,2.803564,...,3.911950,4.0,0.657908,0.062603,0.703334,0.016357,0.077557,3.334964,0.981396,4.653439
4,13-14,35,17.569546,5,0.398417,0.135417,0.038974,0.001114,0.058030,2.031057,...,3.481813,3.0,0.664028,0.112386,0.871088,0.024888,0.081805,2.863172,1.493294,4.908294
5,14-15,31,17.522124,5,0.353838,0.169811,0.020787,0.000671,0.057741,1.789978,...,3.464474,3.0,0.589731,0.151888,0.491148,0.015843,0.072914,2.260339,0.950608,4.374851
6,15-16,44,18.298555,5,0.480912,0.088526,0.105841,0.002405,0.057055,2.510402,...,3.423276,3.0,0.801520,0.055648,2.623551,0.059626,0.114275,5.028112,3.577569,6.856517
7,16-17,59,17.045455,5,0.692267,0.027175,0.822489,0.013940,0.072607,4.283822,...,4.356429,5.0,0.692267,0.027175,0.822489,0.013940,0.072607,4.283822,0.836429,4.356429
8,17-18,65,14.850640,5,0.875383,0.006594,4.976050,0.076555,0.143892,9.352966,...,8.633507,6.0,0.729486,0.010672,1.038822,0.015982,0.083319,5.415738,0.958913,4.999143
9,18-19,23,14.850640,5,0.309751,0.212110,0.010240,0.000445,0.067782,1.558995,...,4.066943,3.0,0.516252,0.198887,0.271660,0.011811,0.079148,1.820415,0.708678,4.748908

In [47]:
def servidores_optimos(lam, mu, umbral_wq_m=5, rho_max=0.85, c_max=20):

    for c in range(1, c_max + 1):

        metrics = metricas_mmc(lam, mu, c)

        if metrics[0] is None:
            continue

        rho = metrics[0]
        Wq_m = metrics[6]

        if rho < rho_max and Wq_m <= umbral_wq_m:

            return (c,) + metrics   # une servidores con todas las métricas

    return (None,)*9


df[[
    "s_o",
    "rho_o",
    "P0_o",
    "Lq_o",
    "Wq_h_o",
    "Ws_h_o",
    "Ls_o",
    "Wq_m_o",
    "Ws_m_o"
]] = df.apply(
    lambda row: servidores_optimos(row["lambda"], row["mu"]),
    axis=1,
    result_type="expand"
)
df

,hora,lambda,mu,s,rho,P0,Lq,Wq_h,Ws_h,Ls,...,Ws_m,s_o,rho_o,P0_o,Lq_o,Wq_h_o,Ws_h_o,Ls_o,Wq_m_o,Ws_m_o
0,9-10,50,19.402460,5,0.515399,0.073847,0.153493,0.003070,0.054610,2.730486,...,3.276583,4.0,0.644248,0.067047,0.627159,0.012543,0.064083,3.204152,0.752591,3.844982
1,10-11,60,17.099906,5,0.701758,0.025614,0.895652,0.014928,0.073407,4.404443,...,4.404443,5.0,0.701758,0.025614,0.895652,0.014928,0.073407,4.404443,0.895652,4.404443
2,11-12,58,17.099906,5,0.678366,0.029591,0.725931,0.012516,0.070996,4.117762,...,4.259754,4.0,0.847958,0.018897,3.822626,0.065907,0.124387,7.214457,3.954441,7.463232
3,12-13,43,16.339678,5,0.526326,0.069682,0.171933,0.003998,0.065199,2.803564,...,3.911950,4.0,0.657908,0.062603,0.703334,0.016357,0.077557,3.334964,0.981396,4.653439
4,13-14,35,17.569546,5,0.398417,0.135417,0.038974,0.001114,0.058030,2.031057,...,3.481813,3.0,0.664028,0.112386,0.871088,0.024888,0.081805,2.863172,1.493294,4.908294
5,14-15,31,17.522124,5,0.353838,0.169811,0.020787,0.000671,0.057741,1.789978,...,3.464474,3.0,0.589731,0.151888,0.491148,0.015843,0.072914,2.260339,0.950608,4.374851
6,15-16,44,18.298555,5,0.480912,0.088526,0.105841,0.002405,0.057055,2.510402,...,3.423276,3.0,0.801520,0.055648,2.623551,0.059626,0.114275,5.028112,3.577569,6.856517
7,16-17,59,17.045455,5,0.692267,0.027175,0.822489,0.013940,0.072607,4.283822,...,4.356429,5.0,0.692267,0.027175,0.822489,0.013940,0.072607,4.283822,0.836429,4.356429
8,17-18,65,14.850640,5,0.875383,0.006594,4.976050,0.076555,0.143892,9.352966,...,8.633507,6.0,0.729486,0.010672,1.038822,0.015982,0.083319,5.415738,0.958913,4.999143
9,18-19,23,14.850640,5,0.309751,0.212110,0.010240,0.000445,0.067782,1.558995,...,4.066943,3.0,0.516252,0.198887,0.271660,0.011811,0.079148,1.820415,0.708678,4.748908

In [48]:
import simpy
import random
import numpy as np

def simular_agencia(lam, mu, ventanillas, tiempo_sim=480):

    esperas = []

    def cliente(env, ventanillas):

        llegada = env.now

        with ventanillas.request() as req:
            yield req

            espera = env.now - llegada
            esperas.append(espera)

            servicio = random.expovariate(mu)
            yield env.timeout(servicio)

    def generador(env, ventanillas):

        while True:
            yield env.timeout(random.expovariate(lam))
            env.process(cliente(env, ventanillas))

    env = simpy.Environment()
    recurso = simpy.Resource(env, capacity=ventanillas)

    env.process(generador(env, recurso))

    env.run(until=tiempo_sim)

    return {
        "clientes": len(esperas),
        "espera_promedio": np.mean(esperas),
        "p95": np.percentile(esperas,95)
    }

In [49]:
simulaciones = []

for _, row in df.iterrows():

    lam = row["lambda"]/60
    mu = row["mu"]/60

    for v in range(2,10):

        resultado = simular_agencia(lam, mu, v)

        simulaciones.append({
            "hora": row["hora"],
            "ventanillas": v,
            "espera_promedio": resultado["espera_promedio"],
            "espera_p95": resultado["p95"],
            "clientes": resultado["clientes"]
        })

df_sim = pd.DataFrame(simulaciones)

df_sim

     hora  ventanillas  espera_promedio  espera_p95  clientes
0    9-10            2        62.248381  105.986624       319
1    9-10            3         6.951240   23.973204       414
2    9-10            4         0.716142    4.434555       396
3    9-10            5         0.070953    0.489583       413
4    9-10            6         0.029778    0.000000       401
..    ...          ...              ...         ...       ...
75  18-19            5         0.011116    0.000000       185
76  18-19            6         0.000000    0.000000       175
77  18-19            7         0.000000    0.000000       189
78  18-19            8         0.000000    0.000000       170
79  18-19            9         0.000000    0.000000       194

[80 rows x 5 columns]